# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d07c1e3b17cbe386dc541295696be4e1bbdd290698490fe230274f5ff862d1fe13c7dda0bfb2053e921e83f509beef36a3a65eb3f93dead7b57bd5aeeafea4a6

test:
  secret_key_base: 40f6ef8dfa594aef0b0ef7ed02df60d1d1ba9c879f31ce0dbd032c252a5de0793d8d86948a70e89b1d7b262ba6c44badcdf41a42433f00cfbb5a237c733cfe19

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
